# Generated by Django 2.2.28 on 2025-03-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20250319_1448'),
        ('recipes', '0003_auto_20250313_1415'),
    ]

    operations = [
    ]
